DROP TABLE DEPARTMENT;
/
DROP TABLE EMPLOYEE;
/

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER PRIMARY KEY, 
DEPARTMENT_NAME VARCHAR2(30)
);
/
CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER PRIMARY KEY, 
EMP_FIRSTNAME VARCHAR2(30), 
EMP_LASTNAME VARCHAR2(30), 
DEPARTMENT_ID INTEGER, 
SALARY NUMBER, 
EMP_EMAIL VARCHAR2(30),


CONSTRAINT FK_EMPLOYEE_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
/

CREATE SEQUENCE EMPLOYEE_SEQUENCE
START WITH 100
INCREMENT BY 1;
/
CREATE SEQUENCE DEPARTMENT_SEQUENCE
START WITH 1
INCREMENT BY 1;
/
--triggers after insert
CREATE OR REPLACE TRIGGER EMPLOYEE_ON_INSERT
  BEFORE INSERT ON EMPLOYEE
  FOR EACH ROW
BEGIN
  SELECT EMPLOYEE_SEQUENCE.NEXTVAL
  INTO :NEW.EMPLOYEE_ID
  FROM DUAL;
END;

CREATE OR REPLACE TRIGGER DEPARTMENT_ON_INSERT
  BEFORE INSERT ON DEPARTMENT
  FOR EACH ROW
BEGIN
  SELECT DEPARTMENT_SEQUENCE.NEXTVAL
  INTO :NEW.DEPARTMENT_ID
  FROM DUAL;
END;

--Inserting values into departments
INSERT INTO DEPARTMENT VALUES('','Software');
INSERT INTO DEPARTMENT VALUES('','Hardware');
INSERT INTO DEPARTMENT VALUES('','QA');
/
--Inserting Values into Employee Table
INSERT INTO EMPLOYEE VALUES('','Wilebr','Barquero',1,45000,'wb@gmail.com');
INSERT INTO EMPLOYEE VALUES('','Ric','Rose',2,50000,'rr@gmail.com');
INSERT INTO EMPLOYEE VALUES('','Leo','Messi',3,80000,'lm@gmail.com');
INSERT INTO EMPLOYEE VALUES('','Lara','Croft',3,40000,'LC@gmail.com');
INSERT INTO EMPLOYEE VALUES('','Chelsea','Obaya',2,55000,'co@gmail.com');
/